spring:
  application:
    name: bookity

  jpa:
    generate-ddl: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  flyway:
    locations: "classpath:/db/migration/{vendor}"
    validate-migration-naming: true
    default-schema: bookity

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:ardaonur1111@gmail.com}
    password: ${MAIL_PASSWORD:ffrjtiucklsklymu}
    properties:
      mail.smtp.auth : true
      mail.smtp.starttls.enable : true

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
